### ISSUE TITLE
Any chance this'll work on Proxmox 8.2.4?

### ISSUE THREAD

**Issue by TheDimensionofEternity** [thenickdude/pve-qemu#3]
Sorry to be a bother, would this work on Proxmox 8.2.4?
I'm not sure what the important differences are to the official version.

**Comment by thenickdude** [comment]
Which branch/feature are you asking about?

**Comment by TheDimensionofEternity** [comment]
I'm following a guide to run MIPS based architecture, this was the repository it said to install, though the guide only shows Proxmox 6 as the latest.
Guide: https://www.nicksherlock.com/2017/08/emulating-mips-guests-in-proxmox/

**Comment by TheDimensionofEternity** [comment]
Just realized, wrong branch ('alien-architectures') though my question still stands.

**Comment by thenickdude** [comment]
I'll rebase it on the newer QEMU version sometime over the next couple of days and let you know.

**Comment by TheDimensionofEternity** [comment]
Alright, thanks!

**Comment by thenickdude** [comment]
I've published a new guide and new branch for Proxmox 8 now:

https://www.nicksherlock.com/2024/09/emulating-mips-guests-in-proxmox-8/

**Comment by TheDimensionofEternity** [comment]
Thank you!
